### ISSUE TITLE
Sensor reports "unknown" value

### ISSUE THREAD

**Issue by pyarr** [Limych/ha-apparent-temperature#117]
Hello,

I'm hoping someone can help me fix an issue I'm having with Temperature Feels Like. I feel like I'm missing something simple...

I have installed Temperature Feels Like v0.3.7 via HACS.
I have added the following to my configuration.yaml:
```
sensor:
  - platform: temperature_feels_like
    name: "Office temperature feels like"
    source:
      - sensor.office_temperature_sensor_temperature
      - sensor.office_temperature_sensor_humidity
```
The sensor then only reports "Unknown".
![image](https://user-images.githubusercontent.com/37237829/234366301-0d6ccd70-0760-4d14-8544-d2a302fe2548.png)

There are two entries in the logs related to Temperature Feels Like:
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/temperature_feels_like/sensor.py:182
Integration: temperature_feels_like (documentation, issues)
First occurred: 19:03:41 (1 occurrences)
Last logged: 19:03:41

Error doing job: Exception in callback TemperatureFeelingSensor.async_added_to_hass.<locals>.sensor_startup(<Event homeassistant_start[L]>) at /config/custom_components/temperature_feels_like/sensor.py:176
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1114, in _onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 641, in async_run_job
    return self.async_run_hass_job(HassJob(target), *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 593, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/temperature_feels_like/sensor.py", line 182, in sensor_startup
    domain = split_entity_id(state.entity_id)[0]
AttributeError: 'NoneType' object has no attribute 'entity_id'
```

```
Logger: homeassistant.helpers.entity
Source: util/unit_conversion.py:379
First occurred: 19:03:41 (1 occurrences)
Last logged: 19:03:41

Update for sensor.office_temperature_feels_like fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 755, in async_device_update
    raise exc
  File "/config/custom_components/temperature_feels_like/sensor.py", line 318, in async_update
    self._temp_val = temp = self._get_temperature(self._temp)  # °C
  File "/config/custom_components/temperature_feels_like/sensor.py", line 258, in _get_temperature
    temperature = TemperatureConverter.convert(
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 379, in convert
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: % is not a recognized temperature unit.

```

Any pointers would be greatly appreciated.

**Comment by michaelcrossland1979** [comment]
I'm having the same but yet I know for a fact that the sensor are reporting to HA as I have tried to make a template sensor and I can see the info from those sensors being ued and gives me a return in the template part of HA. I really could use this bad need ti get it setup and working so that I can get my automations set right to help keep the cooling under control.

Here is what HA is kicking at me for your tool.
`Logger: homeassistant.helpers.entity
Source: util/unit_conversion.py:379
First occurred: 12:52:11 PM (13 occurrences)
Last logged: 1:06:16 PM

Update for sensor.bedroom_feels_like_temperature fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 554, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_device_update
    await self.async_update()
  File "/config/custom_components/temperature_feels_like/sensor.py", line 318, in async_update
    self._temp_val = temp = self._get_temperature(self._temp)  # °C
  File "/config/custom_components/temperature_feels_like/sensor.py", line 258, in _get_temperature
    temperature = TemperatureConverter.convert(
  File "/usr/src/homeassistant/homeassistant/util/unit_conversion.py", line 379, in convert
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: % is not a recognized temperature unit.
`
