### ISSUE TITLE
Error due Sensor Startup

### ISSUE THREAD

**Issue by LuckyTriple7** [Limych/ha-apparent-temperature#15]
HA 2021.5.4

2021-05-15 08:21:06 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback EventBus.async_listen_once.<locals>._onetime_listener(<Event homeassistant_start[L]>) at /usr/src/homeassistant/homeassistant/core.py:809
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 823, in _onetime_listener
    self._hass.async_run_job(listener, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 443, in async_run_job
    return self.async_run_hass_job(HassJob(target), *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 424, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/temperature_feels_like/sensor.py", line 146, in sensor_startup
    self._name = state.attributes["friendly_name"]
KeyError: 'friendly_name'

Configuration.yaml
  - platform: temperature_feels_like
    source: weather.dwd_weather_bad_liebenzell

**Comment by Limych** [comment]
Please open a bug report by filling out the provided template.

**Comment by LuckyTriple7** [comment]
Sorry about the circumstances.
I used a different weather provider, it works now.
